version: '3.1'

services:
  joomla:
    image: joomla:3.8.7-php7.0-apache
    restart: always
    links:
      - joomladb:mysql
    ports:
      - 8080:80
    environment:
      JOOMLA_DB_HOST: joomladb
      JOOMLA_DB_PASSWORD: example
    #volumes:
      #- ./payment_begateway:/var/www/html/plugins/j2store/payment_begateway

  joomladb:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
